services:
  - type: web
    name: shopdue-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
