"use client";
import {useEffect,useState} from "react"; import {useParams} from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8080";
type C={id:number,name:string,phone?:string,address?:string}; type T={id:number,type:"CREDIT"|"PAYMENT",amount:number,note?:string,transactionDate:string,dueDate?:string};
export default function CustomerPage(){const p=useParams(); const id=String(p.id); const[c,setC]=useState<C|null>(null),[ts,setTs]=useState<T[]>([]),[type,setType]=useState<"CREDIT"|"PAYMENT">("CREDIT"),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[due,setDue]=useState(""),[msg,setMsg]=useState("");
 async function load(){const [a,b]=await Promise.all([fetch(API+"/api/customers/"+id),fetch(API+"/api/customers/"+id+"/transactions")]);setC(await a.json());setTs(await b.json())} useEffect(()=>{load()},[id]);
 async function save(){if(!amount||Number(amount)<=0)return;await fetch(API+"/api/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:Number(id),type,amount,note,dueDate:due||null})});setAmount("");setNote("");setDue("");setMsg("Saved successfully");load();setTimeout(()=>setMsg(""),2000)}
 const credit=ts.filter(x=>x.type==="CREDIT").reduce((s,x)=>s+Number(x.amount),0),paid=ts.filter(x=>x.type==="PAYMENT").reduce((s,x)=>s+Number(x.amount),0),balance=Math.max(0,credit-paid);
 return <main className="wrap"><a href="/" className="muted">← Dashboard</a><div className="nav"><div><div className="brand">{c?.name||"Customer"}</div><div className="muted">{c?.phone||"No phone number"}</div></div>{c?.phone&&<a className="btn" target="_blank" href={"https://wa.me/"+c.phone.replace(/\D/g,"")+"?text="+encodeURIComponent("Hi "+c.name+", your current pending balance is ₹"+balance.toLocaleString("en-IN")+". Please settle it when convenient.")}>Remind on WhatsApp</a>}</div>
 <section className="grid"><div className="card"><div className="muted">Total credit</div><div className="value">₹{credit.toLocaleString("en-IN")}</div></div><div className="card"><div className="muted">Paid</div><div className="value">₹{paid.toLocaleString("en-IN")}</div></div><div className="card"><div className="muted">Balance due</div><div className="value">₹{balance.toLocaleString("en-IN")}</div></div></section>
 <section className="section card"><h2>Add transaction</h2><div className="form"><select value={type} onChange={e=>setType(e.target.value as any)}><option value="CREDIT">Credit / Sale</option><option value="PAYMENT">Payment received</option></select><input type="number" min="1" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/>{type==="CREDIT"&&<input type="date" value={due} onChange={e=>setDue(e.target.value)}/>}<input placeholder="Note (optional)" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn" onClick={save}>Save transaction</button>{msg&&<span className="pill">{msg}</span>}</div></section>
 <section className="section card"><h2>Transaction history</h2><table className="table"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Note</th><th>Due</th></tr></thead><tbody>{ts.map(x=><tr key={x.id}><td>{x.transactionDate}</td><td>{x.type==="CREDIT"?"Credit":"Payment"}</td><td>₹{Number(x.amount).toLocaleString("en-IN")}</td><td>{x.note||"—"}</td><td>{x.dueDate||"—"}</td></tr>)}</tbody></table>{!ts.length&&<p className="muted">No transactions yet.</p>}</section></main>}