"use client";
import {useEffect,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import {api,apiJson} from "../../../lib/api";
type C={id:number,name:string,phone?:string,address?:string}; type T={id:number,type:"CREDIT"|"PAYMENT",amount:number,note?:string,transactionDate:string,dueDate?:string};
export default function CustomerPage(){
 const p=useParams(),router=useRouter(),id=String(p.id);
 const[c,setC]=useState<C|null>(null),[ts,setTs]=useState<T[]>([]),[type,setType]=useState<"CREDIT"|"PAYMENT">("CREDIT"),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[due,setDue]=useState(""),[msg,setMsg]=useState(""),[editing,setEditing]=useState(false),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const [a,b]=await Promise.all([apiJson<C>("/api/customers/"+id),apiJson<T[]>("/api/customers/"+id+"/transactions")]);setC(a);setName(a.name);setPhone(a.phone||"");setAddress(a.address||"");setTs(b)}catch{router.replace("/")}}
 useEffect(()=>{load()},[id]);
 async function saveTransaction(){if(!amount||Number(amount)<=0)return;setBusy(true);try{await apiJson("/api/transactions",{method:"POST",body:JSON.stringify({customerId:Number(id),type,amount,note,dueDate:type==="CREDIT"?(due||null):null})});setAmount("");setNote("");setDue("");setMsg(type==="CREDIT"?"Credit added":"Payment recorded");await load();setTimeout(()=>setMsg(""),2000)}finally{setBusy(false)}}
 async function saveCustomer(){if(!name.trim())return;setBusy(true);try{await apiJson("/api/customers/"+id,{method:"PUT",body:JSON.stringify({name,phone,address})});setEditing(false);await load()}finally{setBusy(false)}}
 async function deleteCustomer(){if(!confirm("Delete this customer and all of their credit/payment history? This cannot be undone."))return;setBusy(true);try{await api("/api/customers/"+id,{method:"DELETE"});router.replace("/")}finally{setBusy(false)}}
 async function deleteTransaction(tid:number){if(!confirm("Delete this transaction?"))return;await api("/api/transactions/"+tid,{method:"DELETE"});load()}
 const credit=ts.filter(x=>x.type==="CREDIT").reduce((s,x)=>s+Number(x.amount),0),paid=ts.filter(x=>x.type==="PAYMENT").reduce((s,x)=>s+Number(x.amount),0),balance=Math.max(0,credit-paid);
 const overdue=ts.filter(x=>x.type==="CREDIT"&&x.dueDate&&new Date(x.dueDate+"T23:59:59")<new Date() && Number(x.amount)>0);
 const money=(n:number)=>"₹"+n.toLocaleString("en-IN",{maximumFractionDigits:2});
 return <main className="wrap"><a href="/" className="muted">← Dashboard</a>
 <div className="nav"><div><div className="brand">{c?.name||"Customer"}</div><div className="muted">{c?.phone||"No phone number"}{c?.address?" · "+c.address:""}</div></div><div className="actions">{c?.phone&&<a className="btn" target="_blank" href={"https://wa.me/"+c.phone.replace(/\D/g,"")+"?text="+encodeURIComponent("Hi "+c.name+", your current pending balance is "+money(balance)+". Please settle it when convenient.")}>WhatsApp</a>}<button className="btn alt" onClick={()=>setEditing(!editing)}>Edit</button><button className="btn dangerBtn" onClick={deleteCustomer} disabled={busy}>Delete</button></div></div>
 {editing&&<section className="card form"><h2>Edit customer</h2><input placeholder="Customer name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Phone number" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="Address (optional)" value={address} onChange={e=>setAddress(e.target.value)}/><div className="actions"><button className="btn" onClick={saveCustomer} disabled={busy}>Save changes</button><button className="btn alt" onClick={()=>setEditing(false)}>Cancel</button></div></section>}
 <section className="grid three"><div className="card"><div className="muted">Total credit</div><div className="value">{money(credit)}</div></div><div className="card"><div className="muted">Paid</div><div className="value">{money(paid)}</div></div><div className="card"><div className="muted">Balance due</div><div className="value">{money(balance)}</div></div></section>
 {overdue.length>0&&<div className="notice dangerText">⚠ {overdue.length} overdue credit {overdue.length===1?"entry":"entries"} · {money(overdue.reduce((s,x)=>s+Number(x.amount),0))}</div>}
 <section className="section card"><h2>{type==="CREDIT"?"Add Credit":"Record Payment"}</h2><div className="form"><select value={type} onChange={e=>setType(e.target.value as "CREDIT"|"PAYMENT")}><option value="CREDIT">Credit / Sale</option><option value="PAYMENT">Payment received</option></select><input type="number" min="0.01" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/>{type==="CREDIT"&&<input type="date" value={due} onChange={e=>setDue(e.target.value)}/>}<input placeholder="Note / item description (optional)" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn" onClick={saveTransaction} disabled={busy}>{type==="CREDIT"?"Add Credit":"Record Payment"}</button>{msg&&<span className="pill">{msg}</span>}</div></section>
 <section className="section card"><h2>Transaction history</h2><table className="table"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Note</th><th>Due</th><th></th></tr></thead><tbody>{ts.map(x=><tr key={x.id}><td>{x.transactionDate}</td><td>{x.type==="CREDIT"?"Credit":"Payment"}</td><td>{money(Number(x.amount))}</td><td>{x.note||"—"}</td><td>{x.dueDate||"—"}</td><td><button className="linkBtn dangerText" onClick={()=>deleteTransaction(x.id)}>Delete</button></td></tr>)}</tbody></table>{!ts.length&&<p className="muted">No transactions yet.</p>}</section>
 </main>
}