"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8080";
type C={id:number,name:string,phone?:string,address?:string}; type D={customers:number,totalCredit:number,totalPaid:number,outstanding:number,overdueTransactions:number};
export default function Home(){const[d,setD]=useState<D|null>(null),[cs,setCs]=useState<C[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch(API+"/api/dashboard"),fetch(API+"/api/customers")]);setD(await a.json());setCs(await b.json())}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function add(){if(!name.trim())return;await fetch(API+"/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,phone})});setName("");setPhone("");setShow(false);load()}
 const money=(n:number)=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});
 return <main className="wrap"><nav className="nav"><div><div className="brand">ShopDue</div><div className="muted">Your shop's simple credit ledger</div></div><button className="btn" onClick={()=>setShow(!show)}>+ Customer</button></nav>
 {show&&<div className="card form"><input placeholder="Customer name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Phone number (optional)" value={phone} onChange={e=>setPhone(e.target.value)}/><div className="actions"><button className="btn" onClick={add}>Save customer</button><button className="btn alt" onClick={()=>setShow(false)}>Cancel</button></div></div>}
 {loading?<p className="muted">Loading…</p>:<><section className="grid"><div className="card"><div className="muted">Customers</div><div className="value">{d?.customers}</div></div><div className="card"><div className="muted">Total credit</div><div className="value">{money(d?.totalCredit||0)}</div></div><div className="card"><div className="muted">Paid</div><div className="value">{money(d?.totalPaid||0)}</div></div><div className="card"><div className="muted">Outstanding</div><div className="value">{money(d?.outstanding||0)}</div></div></section>
 <section className="section card"><div className="row"><div><h2>Customers</h2><div className="muted">{d?.overdueTransactions||0} overdue credit entries</div></div></div><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Action</th></tr></thead><tbody>{cs.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.phone||"—"}</td><td>{c.phone?<a className="btn" href={"https://wa.me/"+c.phone.replace(/\D/g,"")+"?text="+encodeURIComponent("Hi "+c.name+", this is a reminder from the shop regarding your pending credit.")} target="_blank">WhatsApp</a>:<span className="muted">No phone</span>}</td></tr>)}</tbody></table>{!cs.length&&<p className="muted">Add your first customer to start tracking credit.</p>}</section></>}</main>}