"use client";
import {useEffect,useState} from "react"; import {useRouter} from "next/navigation"; import {apiJson,token} from "../lib/api";
type C={id:number,name:string,phone?:string,address?:string,balance?:number}; type D={customers:number,totalCredit:number,totalPaid:number,outstanding:number,overdueTransactions:number};
export default function Home(){const router=useRouter();const[d,setD]=useState<D|null>(null),[cs,setCs]=useState<C[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[show,setShow]=useState(false),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[shop,setShop]=useState("");
useEffect(()=>{if(!token()){router.replace("/login");return}const u=localStorage.getItem("shopdue_user");if(u)try{setShop(JSON.parse(u).shopName||"")}catch{}load()},[]);
async function load(){setLoading(true);try{const [a,b]=await Promise.all([apiJson<D>("/api/dashboard"),apiJson<C[]>("/api/customers")]);const withBalances=await Promise.all(b.map(async c=>{const ts=await apiJson<any[]>(`/api/customers/${c.id}/transactions`);const cr=ts.filter(x=>x.type==="CREDIT").reduce((s,x)=>s+Number(x.amount),0);const pa=ts.filter(x=>x.type==="PAYMENT").reduce((s,x)=>s+Number(x.amount),0);return {...c,balance:Math.max(0,cr-pa)}}));setD(a);setCs(withBalances)}catch{}finally{setLoading(false)}}
async function add(){if(!name.trim())return;try{await apiJson("/api/customers",{method:"POST",body:JSON.stringify({name,phone,address})});setName("");setPhone("");setAddress("");setShow(false);load()}catch{}}
function logout(){localStorage.removeItem("shopdue_token");localStorage.removeItem("shopdue_user");router.replace("/login")}
const money=(n:number)=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2}); const filtered=cs.filter(c=>(c.name+" "+(c.phone||"")).toLowerCase().includes(search.toLowerCase()));
return <main className="wrap"><nav className="nav"><div><div className="brand">ShopDue</div><div className="muted">{shop||"Your shop"} · Credit ledger</div></div><div className="actions"><a className="btn alt" href="/reports">Reports</a><button className="btn alt" onClick={logout}>Logout</button><button className="btn" onClick={()=>setShow(!show)}>+ Customer</button></div></nav>
{show&&<div className="card form"><h2>Add customer</h2><input placeholder="Customer name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Phone number (optional)" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="Address (optional)" value={address} onChange={e=>setAddress(e.target.value)}/><div className="actions"><button className="btn" onClick={add}>Save customer</button><button className="btn alt" onClick={()=>setShow(false)}>Cancel</button></div></div>}
{loading?<p className="muted">Loading…</p>:<><section className="grid"><div className="card"><div className="muted">Customers</div><div className="value">{d?.customers}</div></div><div className="card"><div className="muted">Total credit</div><div className="value">{money(d?.totalCredit||0)}</div></div><div className="card"><div className="muted">Paid</div><div className="value">{money(d?.totalPaid||0)}</div></div><div className="card"><div className="muted">Outstanding</div><div className="value">{money(d?.outstanding||0)}</div></div></section>
<section className="section card"><div className="row"><div><h2>Customers</h2><div className="muted">{d?.overdueTransactions||0} overdue credit entries</div></div></div><input className="search" placeholder="Search by name or phone..." value={search} onChange={e=>setSearch(e.target.value)}/><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Balance</th><th>Action</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.phone||"—"}</td><td><b>{money(c.balance||0)}</b></td><td><div className="actions"><a className="btn" href={"/customers/"+c.id}>View</a>{c.phone&&<a className="btn alt" target="_blank" href={"https://wa.me/"+c.phone.replace(/\D/g,"")+"?text="+encodeURIComponent("Hi "+c.name+", your current pending balance is "+money(c.balance||0)+". Please settle it when convenient.")}>WhatsApp</a>}</div></td></tr>)}</tbody></table>{!filtered.length&&<p className="muted">No matching customers.</p>}</section></>}</main>}